# Yekull Server Configuration
auto: false # watch project and auto-compile

# Stylus Converter Plugin for Jekyll
stylus:
  compress: true
  path: ./css/

# Permalnks Structure
# permalink: /year/month/day/title.html
# permalink: /title.html